name: FullJoin
main: FullJoin\Main
version: 1.0.1
api: [3.0.0-ALPHA11]
author: AryToNeX
description: Allow players to join full servers by custom permission
website: https://github.com/AryToNeX
permissions:
  fulljoin.join:
    default: op
    description: "Allow players to join full servers"
